### ISSUE TITLE
Error en documentación de imports

### ISSUE THREAD

**Issue by arielmol** [SAT-CFDI/python-satcfdi#10]
En la documentación y Readme dice:
```python
from satcfdi import CFDI
....
invoice = CFDI.from_file('comprobante.xml')
```

Pero al usarlos directamente no funciona, en realidad tuve que hacer:
```python
from satcfdi import cfdi
...
cfdi.CFDI.from_file(xmlfile)
```

Es algo que un newbie no entendería, pero un experto lo busca y lo encuentra.

**Comment by satcfdi** [comment]
Resuelto
