### ISSUE TITLE
Documentar el validar un CFDI

### ISSUE THREAD

**Issue by arielmol** [SAT-CFDI/python-satcfdi#15]
En la [parte de validación](https://satcfdi.readthedocs.io/en/stable/pages/getting_started/52_portal_facturacion.html#validacion), en la documentación. Uno asumiría que dice como validad una factura, sin embargo, solo se menciona como validar el RFC y la LCO.

Seria bueno indicar el ejemplo de la validación de un comprobante.

**Comment by arielmol** [comment]
Indagando más a fondo, realmente no encuentro la función para verificar un CFDI, solo la generación del link. Hace tiempo yo solía armar la petición SOAP, pense que no se podía más pero veo que [cfdibills](https://cfdibills.readthedocs.io/en/latest/generated/cfdibills.verifiers.verify.html) sí lo hace.

**Comment by arielmol** [comment]
```
curl --request POST \
  --url https://consultaqr.facturaelectronica.sat.gob.mx/ConsultaCFDIService.svc \
  --header 'Accept: text/xml' \
  --header 'Content-Type: text/xml;charset="utf-8"' \
  --header 'SOAPAction: http://tempuri.org/IConsultaCFDIService/Consulta' \
  --data '
<soapenv:Envelope
   xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
   xmlns:tem="http://tempuri.org/">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:Consulta>
         <!--Optional:-->
         <tem:expresionImpresa>
            <![CDATA[?re=CAU180123GEA&rr=GACM650215GH9&tt=398.39&id=699628be-2f06-4bc9-adc2-860b51eecbca&fe=uDu8/g==]]>
         </tem:expresionImpresa>
      </tem:Consulta>
   </soapenv:Body>
</soapenv:Envelope>'
```

Tomado de [aca](https://developers.sw.com.mx/knowledge-base/servicio-publico-de-consulta-estatus-cfdi-sat/).

**Comment by arielmol** [comment]
```
Autenticación y Headers

Header	Value
Content-Type	text/xml;charset=”utf-8″
SOAPAction	http://tempuri.org/IConsultaCFDIService/Consulta
Accept	text/xml
Parámetros

Propiedad	Uso	Descripción
re	Requerido	RFC Emisor
rr	Requerido	RFC Receptor
tt	Requerido	Total declarado en el comprobante
id	Requerido	UUID del comprobante
fe	Requerido	Últimos ocho caracteres del sello digital del emisor
```

**Comment by arielmol** [comment]
Al parecer `fe` funciona cualquier sello valido, podria usarse el del solictante.

**Comment by satcfdi** [comment]
creo que a lo que te refieres es a este metodo
https://satcfdi.readthedocs.io/en/stable/pages/getting_started/50_pac_guide.html#status-comprobante
