### ISSUE TITLE
Lite version to be able to used in a AWS Lambda function (less than 50Mb for the lambda code)

### ISSUE THREAD

**Issue by yoanyr** [SAT-CFDI/python-satcfdi#17]
I am trying to use this excelent library in an AWS lambda function, but AWS has this restriction so any lambda code have to be lees than 50Mb.
  Is it possible to get a lite version of the library that meets this requirement?

Thanks.

**Comment by satcfdi** [comment]
what takes most space is the database, can you program work with out that?
satcfdi-4.3.3-py3-none-any\satcfdi\catalogs\catalogs.db

**Comment by yoanyr** [comment]
Yes, I don't need the dB.

**Comment by satcfdi** [comment]
Due to limited resources, you can try forking the repo and make the changes then do a PR request for review

**Comment by arielmol** [comment]
Layers can be any size, this code should not be in the function anyway. Use a layer.
