### ISSUE TITLE
Descarga de Opinion de cumplimiento

### ISSUE THREAD

**Issue by Atjoms** [SAT-CFDI/python-satcfdi#18]
Buen dia
Me intereso mucho esta libreria, disculpen si mi duda es muy tonta actualmente estoy intentando descargar opiniones de cumplimiento y constancias de situación fiscal, estas ultimas las he podido descargar sin problema pero la opinión de cumplimiento me lleva solo hasta esta pagina el login funciona bien si continua el seguimiento mediante POST me lleva a una pagina donde se carga con js dinámicamente y ahí se genera la opinión de cumplimiento creo que estoy haciendo algo mal puesto que no me da el pdf se que no se pueden cargar dinamicamente con request pero no se como seguir a partir de ahi

estoy usando el apartado de satcfdi.portal

<html>
    <head>
        <META HTTP-EQUIV="expires" CONTENT="0">
    </head>
    <body>

        <form method="POST" enctype="application/x-www-form-urlencoded" action="/nidp/app/login?id=contr-dual-eFirma-totp&sid=1&option=credential&sid=1&target=https%3A%2F%2Flogin.mat.sat.gob.mx%2Fnidp%2Foauth%2Fnam%2Fauthz%3Fclient_id%3D50bffab8-793c-41c4-b639-9abe2a93cb2c%26redirect_uri%3Dhttps%3A%2F%2Fptsc32d.clouda.sat.gob.mx%3A443%2Foauth2%2Fcallback%26response_type%3Dcode%26scope%3Dopenid%2Bmscontribuyente%26code_challenge%3Dy4HdQ3AgiAwtWlHZk5VvMA8fhALgVMbNmSsmh7556Fw%26code_challenge_method%3DS256%26response_mode%3Dform_post%26nonce%3D638529869542239366.N2FlMmExNDEtNGVlNC00YWJlLWJlOTUtMDQwM2E1OWU0OGY0ZGZiOGMxYjMtNDc5MS00ZjRiLThmZGQtNGYyYjRmZjg0MjI4%26state%3DCfDJ8HxmGmhAPKFBkbW3wAEGt_tahVKr-vk2_HV8Uk6XFgeLDSq04WJHZehy_xGuUNBao84EXRbaHaRe--yF5gH5dJ6hm5rmaRwysFHynRm0D4ZN7bK0WA77-FJD1GrvhwY0YNyA7ZPbXLZl-FbSzxAjRirDuFeZSnWMg_IgXxBMwxLezwL2vfJl5zY5KPj6jPAkRuMA-nKa3uyrHFS4oVdcu4H0OQnKgjypZBO4TEdF0f9dvoJVn7iKBZ3woDaUMLaqi2BXW2pBWup_UCZCKZavq0Wii8J67LWI5yIQNfamj839jUR8toK2BW6x-ZrgVBo0JOKyabUl6tKbTW2k7ABlUjjmKz01vsDGx1Y6emjzKm2p00_PKFegk1vBh3n5YF4d5G_meXolUmhwXXjzkwqeDhE%26x-client-SKU%3DID_NETSTANDARD2_0%26x-client-ver%3D6.10.0.0"></form>

        <script language="JavaScript">
            
        </script>
    </body>
</html>

**Comment by satcfdi** [comment]
este es el codigo que yo uso
```

import os

from satcfdi.models import Signer
from satcfdi.portal import SATPortalConstancia

from data.secret_manager import secret_client

fiel = Signer.load(...)

# GET CONSTANCIA
sp = SATPortalConstancia(fiel)

res = sp.generar_constancia()
with open('out/constancia.pdf', 'wb') as f:
    f.write(res)

```

**Comment by Atjoms** [comment]
muchas gracias por contestar tambien uso un codigo parecido para la constancia de situacion pero mi duda es con la opinion de cumplimiento

yo hablo de SATPortalOpinionCumplimiento

**Comment by satcfdi** [comment]
si la funcionalidad de SATPortalOpinionCumplimiento no la termine

**Comment by Atjoms** [comment]
Ok muchas gracias me podrias decir que deberia usar intente con request-html pero simplemente no pude lograrlo actualmente tuve que usar playwright sabes si deberia poderse con request-html o algo que me recomiendes para intentar hacerlo,

sigo intentando que funcione con request-html

**Comment by satcfdi** [comment]
la verdad no estoy seguro con que, por lo que revise descargar la Opinion de Cumplimiento es mas complicado que la constancia de situacion fiscal
