### ISSUE TITLE
Codigo 5000 sin cfdi´s

### ISSUE THREAD

**Issue by darkleono** [SAT-CFDI/python-satcfdi#22]
Solicitud creada y aceptada con codigo 5000 pero con 0 Cfdis, sin embargo entrando desde el portal si hay cfdis en las fechas seleccionadas.

'CodigoEstadoSolicitud': '5000', 'NumeroCFDIs': 0, 'Mensaje': 'Solicitud Aceptada'}

Alguna idea de porque no me detecta los cfdis?
He intentado con multiples rangos de fechas, y distintos Contribuyentes-.

Muchas gracias.

**Comment by satcfdi** [comment]
Es necesario esperarse a que la solicitud este en estado terminado para ver el numero de CFDIs
https://satcfdi.readthedocs.io/en/stable/pages/getting_started/45_cfdi_descarga_massiva.html

**Comment by arielmol** [comment]
Ese es el mismo error que me sale, pero ligeramente diferente en #19

**Comment by arielmol** [comment]
Como que recientemente cambio el SAT o habra mucha carga, pero desde un "Solicitud Aceptada" hasta una descarga real, a mi me tomo 3 días!.

**Comment by arielmol** [comment]
Hay que hacer polling y esperar un `'EstadoSolicitud': 3`
