### ISSUE TITLE
Representación impresa sobrepasa los márgenes en PDF

### ISSUE THREAD

**Issue by Ahuahuachi** [SAT-CFDI/python-satcfdi#24]
**Describe the bug**
Al generar un PDF a partir de un CFDI, la sección Timbre Fiscal Digital sobrepasa los márgenes de la hoja.

**To Reproduce**
1. Generar un objeto CFDI
2. Renderizar su representación impresa con `render.pdf_bytes()`

**Expected behavior**
El texto debería mantenerse dentro de los márgenes

**Screenshots**
![image](https://github.com/user-attachments/assets/b098e0fa-c462-41f1-94b8-ba18efa527d7)

**Comment by satcfdi** [comment]
tienes idea de que cambio de codigo corregiria eso?

**Comment by Ahuahuachi** [comment]
Creo que será cuestión de jugar con la posición y los estilos de la tabla en el template.
Tal vez colocar el folio y la fecha  en diferentes filas así como el RFC y el no. de certificado pueda ayudar.

Lamentablemente no he tenido tiempo de generar una propuesta de PR y por mientras creé el issue por si alguien más quisiera trabajar en ello o hasta que me pueda dar un tiempo para trabajar en ello.

**Comment by ArmandoSep** [comment]
@Ahuahuachi  Podrías compartir un ejemplo para usar el Timbre Fiscal Digital? Estoy generando el comprobante, pero no se timbra.

**Comment by Ahuahuachi** [comment]
@ArmandoSep el proceso de timbrado lo realiza el SAT por medio de un Proveedor Autorizado de Certificación (PAC), la librería no genera el timbre.

**Comment by ArmandoSep** [comment]
Gracias, @Ahuahuachi! Hay algún PAC que recomiendes? Vi que hay integración con comercio digital, finkok, mysuite, prodigia y swsapien
