### ISSUE TITLE
Can't read file when XML uses on xmlns:schemaLocation http://www.sat.gob.mx/registrofiscal and cfdiregistrofiscal.xsd

### ISSUE THREAD

**Issue by jafrancov** [SAT-CFDI/python-satcfdi#4]
Hi! Thanks for this amazing tool, I have this issue, when I'm trying to read a XML that uses this structure:

```
<registrofiscal:CFDIRegistroFiscal xmlns:registrofiscal="http://www.sat.gob.mx/registrofiscal" 
xmlns:schemaLocation="http://www.sat.gob.mx/registrofiscal 
http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd" 
Version="1.0" Folio="000000000000"/>
```
It throws an exception:
` xmlns:schemaLocation: 'http://www.sat.gob.mx/registrofiscal http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd' is not a valid URI`

I have detect that it is correctly declared in `transforms/schemas.py`, but not working or it doesn't recognize it.

If manually remove the `http://www.sat.gob.mx/registrofiscal ` url, it works, it allows me to work with it, but, the user must remove it manually.

**Comment by satcfdi** [comment]
Thanks for opening the issue, I'll take a look at it

**Comment by satcfdi** [comment]
Looks like your xml is invalid, error comes for the lxml library
it has the incorrect namespace for the schemaLocation
the correct value is:
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

```
from lxml import etree

parser = etree.XMLParser(no_network=True, remove_comments=True, remove_blank_text=True)
data = b"""<?xml version="1.0" encoding="utf-8" ?>
<registrofiscal:CFDIRegistroFiscal xmlns:registrofiscal="http://www.sat.gob.mx/registrofiscal" 
xsi:schemaLocation="http://www.sat.gob.mx/registrofiscal 
http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Version="1.0" Folio="000000000000"/>
"""

res = etree.fromstring(data, parser=parser)
```
