### ISSUE TITLE
 is not a valid URI, line 28: Error leyendo algunos CFDI (ejemplo incluido)

### ISSUE THREAD

**Issue by arielmol** [SAT-CFDI/python-satcfdi#7]
Marca error al intentar cargar  el siguiente XML
> xmlns:schemaLocation: 'http://www.sat.gob.mx/registrofiscal http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd' is not a valid URI, line 28, column 182 (b66ccf54-df9f-4296-b9cd-fdfc76de11a1.xml, line 28)

[f6b3ecfa-833e-4a5e-934a-2becd000d68f.tar.gz](https://github.com/SAT-CFDI/python-satcfdi/files/12255177/f6b3ecfa-833e-4a5e-934a-2becd000d68f.tar.gz)

Sin embargo el archivo es válido, se puede comprobar en el SAT, y el proyecto cfdibills lo carga bien.

Además, ese archivo fue descargado por el mismo satcfdi via Descarga Masiva directo del SAT.

**Comment by satcfdi** [comment]
el archivo XML es invalido

esta linea
<registrofiscal:CFDIRegistroFiscal **xmlns**:schemaLocation="http://www.sat.gob.mx/registrofiscal http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd"

deberia de ser
<registrofiscal:CFDIRegistroFiscal **xsi**:schemaLocation="http://www.sat.gob.mx/registrofiscal http://www.sat.gob.mx/sitio_internet/cfd/cfdiregistrofiscal/cfdiregistrofiscal.xsd"

**Comment by arielmol** [comment]
Entiendo que el error sea del SAT, pero ese XML es descargado directamente de ellos. Para fines prácticos debe existir al  menos un código de error y que el usuario aplique parches o pueda reportar, ya que el mismo SAT está entregando esos XML.

**Comment by arielmol** [comment]
Una alternativa interesante es ver por qué [cfdibills](https://cfdibills.readthedocs.io/en/latest/index.html) sí lo lee bien y tomar alguna acción especial si es que corresponde. O bien hacer un validador de XML para poder generar una tabla de 'quirks' al estilo que hace el Kernel de Linux con infinidad de hardware que tiene comportamientos raros y anormales.

**Comment by arielmol** [comment]
Tengo mas ejemplos si es necesario, pero creo que todos son iguales

**Comment by satcfdi** [comment]
ok, lo reviso para agregar un work around

**Comment by satcfdi** [comment]
Puedes probar con la version 4.1.3
Saludos

**Comment by satcfdi** [comment]
Corregido en la version 4.1.3
